### PR TITLE
Corrected locale dependent unit test t/idn.t

### PR DESCRIPTION
**Pull request by matsduf**
Fixes issue #102

### CODE REVIEW

**Comment by mattias-p** [comment]
As you describe in the bug report the problem is that the unit test is locale dependent. This fix does not change that. Have you considered forcing C locale instead of (or possibly in addition to) dropping the case sensitivity?

**Comment by matsduf** [comment]
> As you describe in the bug report the problem is that the unit test is locale dependent. This fix does not change that.

Yes and no. In this case the phrase "punycode" will probably be kept in a translated error message, but a solution not based on the error message is better. This will at least work as a work-around that does not make things worse. Maybe there is an error code that could be captured instead.

> Have you considered forcing C locale instead of (or possibly in addition to) dropping the case sensitivity?

Do you mean forcing C locale by resetting the locale in the test code? No, I decided to take the short solution (work-around), but I could create an issue that it should be fixed. Maybe you see that the solution is quick  and easy, or else have the work-around now, and solution later.

**Comment by mattias-p** [comment]
> Maybe there is an error code that could be captured instead.

That would be really nice, but I've come to not expect such things in Perl.

> No, I decided to take the short solution (work-around), but I could create an issue that it should be fixed.

:+1:

**Comment by matsduf** [comment]
This is a work-around to fix #102. Issue #104 has been created for a solution.

**Pull request merged**
