### PR TITLE
Proposition to set up github action

### PR DESCRIPTION
**Pull request by MichaelTimbert**
## Purpose

Propose an CI solution using github action.
If accepted this can close #195 and #119, since it is no longer necessary to test the MANIFEST in the test suite.

## How to test this PR

Github action must be run when  a push is made on [develop, master, releases] or when a pull request is requested.
This must run the test suite and fail if an error is reported.
Same if 'make distcheck' report missing files.

### CODE REVIEW

**Comment by matsduf** [comment]
If we get the same function as #119 or will the CI halt if `MANIFEST,MANIFEST.SKIP` is not updated? If so I think it is better to run it as a `t` file to get as much information as possible.

I am for switching to Github action. We already run that for Zonemaster-Engine. Is this solution the same or are there some differences? I think it should be as equal as possible.

**Comment by MichaelTimbert** [comment]
As discussed in https://github.com/zonemaster/zonemaster-ldns/pull/195 I can create another job in github action to check `MANIFEST.*`. This will improve the readability.

**Comment by matsduf** [comment]
Can you explain what the purpose is of having the MANIFEST checks in both `ci.yml` and `manifest.yml`?

Is this solution the same as the one that we already run in Zonemaster-Engine?

**Comment by MichaelTimbert** [comment]
> Can you explain what the purpose is of having the MANIFEST checks in both `ci.yml` and `manifest.yml`?

None, it's one or the other not both.
Actually Zonemaster-Engine use the `t/manifest.t` method. For the moment, I will remove the verification of the manifest in github-action and keep it with `t/manifest.t` so that it is the same as in zonemaster-Engine.

**Review by matsduf — APPROVED** [review]

**Pull request merged**
