### PR TITLE
Avoid Github control files in dist file

### PR DESCRIPTION
**Pull request by mattias-p**
Account for the new Github PR template in MANIFEST.SKIP.

### CODE REVIEW

**Comment by mattias-p** [comment]
The tests fail because the internet has changed. I'm trying to determine what is the correct thing to do. It should be either to update the unit test or to fix the internet.

**Review by matsduf — DISMISSED** [review]

**Comment by matsduf** [comment]
> The tests fail because the internet has changed. I'm trying to determine what is the correct thing to do. It should be either to update the unit test or to fix the internet.

I tested from a server with both IPv4 and IPv6 access and get no errors. The code I tested is the previous release but there should not be any relevant change.  I have also tested the new code, but with IPv4 only. Temporary glitch? Send an empty commit to restart Travis?

This the server with both IPv4 and IPv6:
```
$ cpanm --test-only -v Zonemaster::LDNS
cpanm (App::cpanminus) 1.7043 on perl 5.026001 built for x86_64-linux-gnu-thread-multi
Work directory is /home/mats.dufberg/.cpanm/work/1622056142.16142
(...)
"/usr/bin/perl" "-Iinc" -MExtUtils::Command::MM -e 'cp_nonempty' -- LDNS.bs blib/arch/auto/Zonemaster/LDNS/LDNS.bs 644
"/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/*.t
t/axfr.t ........... ok   
t/dnssec.t ......... ok    
t/idn.t ............ ok   
t/load_zonefile.t .. ok   
t/netldns.t ........ ok    
t/packet.t ......... ok    
t/regression.t ..... ok   
t/resolver.t ....... ok    
t/rr.t ............. ok    
t/rrlist.t ......... ok    
t/serialize.t ...... ok   
t/threads.t ........ ok   
t/utils.t .......... ok   
t/wireformat.t ..... ok    
All tests successful.
Files=14, Tests=246,  1 wallclock secs ( 0.06 usr  0.03 sys +  0.78 cusr  0.14 csys =  1.01 CPU)
Result: PASS
OK
Successfully tested Zonemaster-LDNS-2.1.0
```

**Comment by pnax** [comment]
I was able to reproduce with `TEST_WITH_NETWORK=1 make test`. When installing from CPAN, I guess the tests are run without network access.
The failing unit test is not related to this PR, so no problem for me to merge as it is if it does not prevent installation from CPAN. However should we discuss at some point how to deal with such failing unit tests using data from the Internet ? (or maybe this has already been discussed in the past ?)

**Comment by matsduf** [comment]
The conclusion before was that installation should be done without running these tests because of the risk that changes "on Internet" will create problem for installation. We should accept that Travis will fail once in a while (it has happened less than once a year) and then adjust the tests.

**Review by matsduf — APPROVED** [review]

**Review by pnax — APPROVED** [review]

**Pull request merged**
